logo: /assets/img/hadjet_vizier_cogham_vidrieg_doshart_nuerkeng_ieh_rogam_nastem_hemsi_shafti_kogog_durath.png
title: Reptilianism.org
description: Perspective-based adventures in fact, because reality is a difference of opinion.
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
